version: 1
build:
  binary: "platined"
genesis:
  chain_id: "platine-1"
  app_state:
    staking:
      params:
        bond_denom: "uplc"
        unbonding_time: "600s"
    mint:
      params:
        mint_denom: "uplc"
    gov:
      deposit_params:
        min_deposit:
        - denom: "uplc"
          amount: '10000000'
        max_deposit_period: "600s"
      voting_params:
        voting_period: "1200s"
accounts:
  - name: alice
    coins: ["500000000000uplc"]
  - name: bob
    coins: ["2000000000000uplc"]
validators:
  - name: alice
    bonded: "20000000000uplc"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["1000000000000000000uplc"]
