version: 1
build:
  binary: "platined"
  ldflags: ["-X github.com/cosmos/cosmos-sdk/version.Name=PlatineChain", "-X github.com/cosmos/cosmos-sdk/version.AppName=platined", "-X github.com/cosmos/cosmos-sdk/version.Version=1.0.0", "-X github.com/cosmos/cosmos-sdk/version.Commit=9d0d1c343754eab78430b046fa9a68cce0594093", "-X github.com/cosmos/cosmos-sdk/version.BuildTags=Platine-Centos7.9-x64"]
genesis:
  chain_id: "platine-1"
  app_state:
    staking:
      params:
        bond_denom: "uplc"
    minter:
      params:
        mint_denom: "uplc"
    gov:
      deposit_params:
        min_deposit:
        - denom: "uplc"
          amount: '10000'
accounts:
  - name: alice
    coins: ["200000000uplc"]
  - name: bob
    coins: ["100000000uplc"]
validators:
  - name: alice
    bonded: "100000000uplc"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["100000uplc"]
