version: "3"
services:
  node:
    build:
      context: .
      args:
        - arch=${ARCH:-x86_64}
    image: platined-local
    container_name: platined-local
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
    environment:
      - MONIKER=node001
      - STAKE_TOKEN=uplc
      - CHAIN_ID=platine-1
      - PASSWORD=platinepwd
    command: ['/opt/chain_run','platine10m200kns6lle7dxfc7fffvma83v3ew87e9ygqk']
